### ISSUE TITLE
Cassandra Store Catalog Function || Remove Store.Metadata.getVersion() from the Bundle example

### ISSUE THREAD

**Issue by spingale-tibco** [TIBCOSoftware/be-contribution#106]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |     6.3.0            |
| OS Type?     |  NA               |
| OS Version?           |     NA            |

### What is the expected behavior?
Need to remove Store.Metadata.getVersion() code from the bundle example.

### What is the actual behavior?
Store.Metadata.getVersion() is not supported for Cassandra Catalog function. As Store.Metadata.getVersion() code is present in bundle example, which throws an exception while executing bundle example from readme.

### Please provide log files.
`2023 May 10 15:39:07:123 GMT +05 CF_SNInfe6 ERROR [$default.be.mt$.Thread.6] - [runtime.service] [inference-class] Got runtime exception while invoking Preprocessor /RuleFunctions/GetGridMedata Arguments <be.gen.Events.GetMetadata@id=[typeId:1016|extId=52a543ae-bad4-43bc-af27-60ba2be147de]>
java.lang.RuntimeException: Error fetching Store version
        at com.tibco.cep.store.functions.MetadataFunctions.getVersion(MetadataFunctions.java:43)
        at be.gen.RuleFunctions.nullGetGridMedata$9y002fEvents$9y002fGetMetadata$.GetGridMedata(nullGetGridMedata$9y002fEvents$9y002fGetMetadata$.java:19)
        at be.gen.RuleFunctions.GetGridMedata.invoke(GetGridMedata.java:11)
        at com.tibco.cep.runtime.session.impl.RuleSessionImpl$4.doTxnWork(RuleSessionImpl.java:1168)
        at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:141)
        at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
        at com.tibco.cep.runtime.session.impl.RuleSessionImpl.preprocessPassthru(RuleSessionImpl.java:1197)
        at com.tibco.cep.runtime.service.cluster.ClusterTaskController$1.doTxnWork(ClusterTaskController.java:78)
        at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:156)
        at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
        at com.tibco.cep.runtime.service.cluster.ClusterTaskController.executeTask(ClusterTaskController.java:103)
        at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2$WorkerTask.run(WorkerBasedControllerV2.java:530)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at com.tibco.cep.runtime.util.CustomBEManagedThread.run(CustomBEManagedThread.java:24)
Caused by: java.lang.UnsupportedOperationException: Method not supported.
        at com.tibco.cep.store.cassandra.CassandraStoreMetadata.getVersion(CassandraStoreMetadata.java:29)
        at com.tibco.cep.store.functions.MetadataFunctions.getVersion(MetadataFunctions.java:41)
        ... 14 more`

**Comment by rakulkar-tibco** [comment]
updated example in be-samples repo

**Comment by spingale-tibco** [comment]
Agree Fixed
