### ISSUE TITLE
Cassandra Store Catalog Function || Getting NullPointerException while executing QueryAgent with Native query and BQL

### ISSUE THREAD

**Issue by spingale-tibco** [TIBCOSoftware/be-contribution#109]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |    6.3.0             |
| OS Type?     |     NA            |
| OS Version?           |         NA        |

### What is the actual behavior?
We are testing QueryAgent with Native query and BQL.
While execution we are getting below execption:
`2023 May 18 16:41:39:250 GMT +05 CSNativeQuery5 INFO [s0-admin-0] - [store.cassandra] :::: Cassandra host /10.69.136.106:9042 is UP now::::
[] /10.69.136.106:9042 did not send an authentication challenge; This is suspicious because the driver expects authentication
2023 May 18 16:41:42:623 GMT +05 CSNativeQuery5 INFO [main] - [store.cassandra] [inference-class] Successfully connected to Cassandra using Contact Points: /10.69.136.106:9042,
2023 May 18 16:41:42:626 GMT +05 CSNativeQuery5 INFO [main] - [user] [inference-class] Connected to Cassandra with name: csnativequery
2023 May 18 16:41:42:626 GMT +05 CSNativeQuery5 INFO [main] - [user] [inference-class] Test
2023 May 18 16:41:42:629 GMT +05 CSNativeQuery5 FATAL [main] - [container.standalone] null
java.lang.NullPointerException
        at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2.start(WorkerBasedControllerV2.java:312)
        at com.tibco.cep.runtime.session.impl.RuleSessionImpl.start(RuleSessionImpl.java:394)
        at com.tibco.cep.runtime.session.impl.RuleSessionManagerImpl.start(RuleSessionManagerImpl.java:252)
        at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.startAll(RuleServiceProviderImpl.java:1215)
        at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:281)
        at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:172)
        at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
System exit requested by thread [main] with status: -1
System.exit(..) will be invoked now with status: -1`

Can you please confirm whether Query Agent is Supported or not with Cassandra Catalog Function

**Comment by rakulkar-tibco** [comment]
yes, query agent is not supported with the Cassandra catalog function.
