### ISSUE TITLE
Getting java.lang.ClassNotFoundException: javax.ws.rs.WebApplicationException while executing FraudDetectionLiveView

### ISSUE THREAD

**Issue by jgandhi-tibco** [TIBCOSoftware/be-contribution#123]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |       6.3.0          |
| OS Type?     |      Windows          | 
| OS Version?           |         10        |

### What is the expected behavior?

BE engine should get start successfully.

### What is the actual behavior?
While starting the be-engine, encountering following exception:
```
023 Jul 24 12:06:18:457 GMT +05 LVLogs_2 FATAL [main] - [container.standalone] javax/ws/rs/WebApplicationException
java.lang.NoClassDefFoundError: javax/ws/rs/WebApplicationException
        at com.streambase.liveview.client.LiveViewConnectionFactory.getConnection(LiveViewConnectionFactory.java:85)
        at com.tibco.cep.liveview.LVConnectionPool.createObject(LVConnectionPool.java:41)
        at com.tibco.cep.liveview.LVConnectionPool.createObject(LVConnectionPool.java:11)
        at com.tibco.be.util.pool.ObjectPool.initialize(ObjectPool.java:70)
        at com.tibco.cep.liveview.LVConnectionPool.initialize(LVConnectionPool.java:36)
        at com.tibco.cep.liveview.LVMetricsStoreProvider.connect(LVMetricsStoreProvider.java:65)
        at com.tibco.cep.runtime.appmetrics.AppMetricsManager.connect(AppMetricsManager.java:138)
        at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.initCluster(RuleServiceProviderImpl.java:834)
        at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:303)
        at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:169)
        at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.WebApplicationException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 11 more
```
### Please provide a unit test that demonstrates the bug.
1. Create the metric/liveview and channel/sb jars from repo and copy it to BE_HOME/lib/ext/tpcl/contrib
2. Copy lv-client.jar and sbclient.jar from SB_Home to BE_HOME/lib/ext/tpcl
3. Start BE studio and import FraudDetectionLiveView example, build ear and start engine

While starting engine, it triggers exception as mentioned above. 
Also, while adding all jars from SB_HOME/lib into BE_HOME/lib/ext/tpcl, it gives another exception. Attaching logs files of both scenairos for reference.

[LVLogs.zip](https://github.com/TIBCOSoftware/be-contribution/files/12142637/LVLogs.zip)

**Comment by rakulkar-tibco** [comment]
Update your classpath in such a way that - SB_HOME/lib is before BE_HOME/eclipse/plugins.
SB_HOME/lib should contain lv-client.jar, sbclient.jar and sb-java-tools.jar.
