### ISSUE TITLE
Cassandra Store Catalog Function || Getting Exception with bundled example

### ISSUE THREAD

**Issue by praagraw-tibco** [TIBCOSoftware/be-contribution#82]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |      6.3.0           |
| OS Type?     |      NA           |
| OS Version?           |      NA           |

Couple of features of bundled example is not working and getting exceptions as mentioned below, attached logs for the same.
1. Show store metadata (4th step in readme)
2. perform the following operations within a transaction on Phone container (9th step in readme)
3. While creating employee concept, "is dept" is provided as "true" however it's storing as false and retrieving the same during get operation. Attached logs for reference.

What is the expected behavior?
Bundled example should work 

What is the actual behavior?
java.lang.RuntimeException: Error fetching Store version
	at com.tibco.cep.store.functions.MetadataFunctions.getVersion(MetadataFunctions.java:43)
	at be.gen.RuleFunctions.nullGetGridMedata$9y002fEvents$9y002fGetMetadata$.GetGridMedata(nullGetGridMedata$9y002fEvents$9y002fGetMetadata$.java:19)
	at be.gen.RuleFunctions.GetGridMedata.invoke(GetGridMedata.java:11)
	at com.tibco.cep.runtime.session.impl.RuleSessionImpl$4.doTxnWork(RuleSessionImpl.java:1168)
	at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:141)
	at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
	at com.tibco.cep.runtime.session.impl.RuleSessionImpl.preprocessPassthru(RuleSessionImpl.java:1197)
	at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2$2.doTxnWork(WorkerBasedControllerV2.java:488)
	at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:156)
	at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
	at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2.executeTask(WorkerBasedControllerV2.java:502)
	at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2$WorkerTask.run(WorkerBasedControllerV2.java:530)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.tibco.cep.runtime.util.CustomBEManagedThread.run(CustomBEManagedThread.java:24)
Caused by: java.lang.UnsupportedOperationException: Method not supported.
	at com.tibco.cep.store.cassandra.CassandraStoreMetadata.getVersion(CassandraStoreMetadata.java:29)
	at com.tibco.cep.store.functions.MetadataFunctions.getVersion(MetadataFunctions.java:41)
	... 14 more
2023 Apr 03 17:47:16:514 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.2] - [user] [inference-class] Put Address[Palo Alto, California] with Id[21095429323600]
2023 Apr 03 17:47:16:515 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.2] - [user] [inference-class] Put Alternate Address[Mountain View, California] with Id[21095434097200]
2023 Apr 03 17:47:16:522 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.2] - [user] [inference-class] Put Phone[212-313-4114:400-300-4000] with Id[21095436079800]
2023 Apr 03 17:47:17:557 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.2] - [user] [inference-class] Put Employee[Bob] with Id[21095441117600]
2023 Apr 03 17:47:27:358 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.5] - [user] [inference-class] Enable Transactions...
2023 Apr 03 17:47:27:358 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.5] - [user] [inference-class] Adding Phone 1...
2023 Apr 03 17:47:27:358 GMT +05 Cass_store_func_Test_V1 INFO [$default.be.mt$.Thread.5] - [user] [inference-class] Adding Phone 2...
2023 Apr 03 17:47:27:631 GMT +05 Cass_store_func_Test_V1 ERROR [$default.be.mt$.Thread.5] - [runtime.service] [inference-class] Got runtime exception while invoking Preprocessor /RuleFunctions/PerformPhoneTransaction Arguments <be.gen.Events.PerformPhoneTransaction@id=[typeId:0|extId=b80d955f-e6d4-4561-b1c4-69aed3a70acb]>
java.lang.IllegalArgumentException: Argument type not valid. Expected type is Item
	at com.tibco.cep.store.functions.ItemFunctions.getValue(ItemFunctions.java:208)
	at com.tibco.cep.store.functions.ItemFunctions.getLong(ItemFunctions.java:97)
	at be.gen.RuleFunctions.nullPerformPhoneTransaction$9y002fEvents$9y002fPerformPhoneTransaction$.PerformPhoneTransaction(nullPerformPhoneTransaction$9y002fEvents$9y002fPerformPhoneTransaction$.java:55)
	at be.gen.RuleFunctions.PerformPhoneTransaction.invoke(PerformPhoneTransaction.java:11)
	at com.tibco.cep.runtime.session.impl.RuleSessionImpl$4.doTxnWork(RuleSessionImpl.java:1168)
	at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:141)
	at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
	at com.tibco.cep.runtime.session.impl.RuleSessionImpl.preprocessPassthru(RuleSessionImpl.java:1197)
	at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2$2.doTxnWork(WorkerBasedControllerV2.java:488)
	at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:156)
	at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
	at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2.executeTask(WorkerBasedControllerV2.java:502)
	at com.tibco.cep.runtime.scheduler.impl.WorkerBasedControllerV2$WorkerTask.run(WorkerBasedControllerV2.java:530)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.tibco.cep.runtime.util.CustomBEManagedThread.run(CustomBEManagedThread.java:24)

[Cass_store_func_Test_V1.log](https://github.com/TIBCOSoftware/be-contribution/files/11145160/Cass_store_func_Test_V1.log)

**Comment by rakulkar-tibco** [comment]
Expected behaviour.Caused by: java.lang.UnsupportedOperationException: Method not supported.
