### ISSUE TITLE
Cassandra Store Catalog Function || Getting exception missing username when Cassandra.yaml has authenticator: AllowAllAuthenticator

### ISSUE THREAD

**Issue by praagraw-tibco** [TIBCOSoftware/be-contribution#84]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| BusinessEvents             |      6.3.0           |
| OS Type?     |                 |     NA
| OS Version?           |       NA          |

### What is the expected behavior?
No exception should be thrown when authenticator: AllowAllAuthenticator in Cassandra.yaml and setUserCredentials function is not used

### What is the actual behavior?
java.lang.RuntimeException: Error occurred while connecting to Store with url[10.69.136.106:9042]
	at com.tibco.cep.store.functions.StoreFunctions.connect(StoreFunctions.java:79)
	at be.gen.RuleFunctions.nullStartUpCassandra$.StartUpCassandra(nullStartUpCassandra$.java:21)
	at be.gen.RuleFunctions.StartUpCassandra.invoke(StartUpCassandra.java:11)
	at com.tibco.cep.runtime.session.impl.RuleFunctionsExecAction.executeComponent(RuleFunctionsExecAction.java:65)
	at com.tibco.cep.kernel.core.rete.ReteWM$2.doTxnWork(SourceFile:549)
	at com.tibco.cep.kernel.core.rete.BeTransaction.run(SourceFile:156)
	at com.tibco.cep.kernel.core.rete.BeTransaction.execute(SourceFile:101)
	at com.tibco.cep.kernel.core.rete.ReteWM.invoke(SourceFile:599)
	at com.tibco.cep.kernel.core.rete.ReteWM.start(SourceFile:230)
	at com.tibco.cep.runtime.session.impl.RuleSessionImpl.start(RuleSessionImpl.java:396)
	at com.tibco.cep.runtime.session.impl.RuleSessionManagerImpl.start(RuleSessionManagerImpl.java:252)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.startAll(RuleServiceProviderImpl.java:1202)
	at com.tibco.cep.runtime.session.impl.RuleServiceProviderImpl.configure(RuleServiceProviderImpl.java:281)
	at com.tibco.cep.container.standalone.BEMain.jumpStart(SourceFile:172)
	at com.tibco.cep.container.standalone.BEMain.main(SourceFile:71)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: username cannot be null
	at com.tibco.cep.store.cassandra.CassandraConnection.connect(CassandraConnection.java:103)
	at com.tibco.cep.store.functions.StoreFunctions.connect(StoreFunctions.java:77)
	... 14 more
Caused by: java.lang.NullPointerException: username cannot be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at com.datastax.oss.driver.internal.core.util.Strings.requireNotEmpty(Strings.java:267)
	at com.datastax.oss.driver.api.core.auth.ProgrammaticPlainTextAuthProvider.<init>(ProgrammaticPlainTextAuthProvider.java:79)
	at com.datastax.oss.driver.api.core.auth.ProgrammaticPlainTextAuthProvider.<init>(ProgrammaticPlainTextAuthProvider.java:63)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.withAuthCredentials(SessionBuilder.java:347)
	at com.tibco.cep.store.cassandra.CassandraConnection.getCqlSessionBuilder(CassandraConnection.java:297)
	at com.tibco.cep.store.cassandra.CassandraConnection.connect(CassandraConnection.java:101)

### Please provide log files.

[username_pwd_test1.log](https://github.com/TIBCOSoftware/be-contribution/files/11145412/username_pwd_test1.log)

**Comment by praagraw-tibco** [comment]
Agree fixed.
[allowAll_setUsercred_V13.log](https://github.com/TIBCOSoftware/be-contribution/files/11210008/allowAll_setUsercred_V13.log)
